apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-labeler-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-labeler-role
rules:
- apiGroups: [""] # Core API group
  resources: ["nodes"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-labeler-rolebinding
subjects:
- kind: ServiceAccount
  name: node-labeler-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: node-labeler-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: node-labeler
spec:
  selector:
    matchLabels:
      app: node-labeler
  template:
    metadata:
      labels:
        app: node-labeler
    spec:
      serviceAccountName: node-labeler-sa
      containers:
      - name: labeler
        image: mcr.microsoft.com/cbl-mariner/busybox:1.35
        command: ["sh", "-c", "echo 'Task completed'; sleep 3600"]
      initContainers:
      - name: init-labeler
        image: mcr.microsoft.com/oss/kubernetes/kubectl:v1.26.3
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: host-data
          mountPath: /var/lib/hyperv/.kvp_pool_3
        command: ["/bin/sh", "-c"] 
        args:
          - |
            for kv in $(cat /var/lib/hyperv/.kvp_pool_3 | sed 's/\x0/ /g;s/  */ /g'  | sed -E 's/([^ ]+) ([^ ]+)/\1=\2\n/g; s/ ([^ ]+)$/=\1/'); do
              echo $kv
              kubectl label node "$NODE_NAME" "hyperv/$kv" --overwrite 
            done
      volumes:
      - name: host-data
        hostPath:
          path: /var/lib/hyperv/.kvp_pool_3
