apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: local-nvme-scratch
  labels:
    app: local-nvme-scratch
spec:
  selector:
    matchLabels:
      name: local-nvme-scratch
  template:
    metadata:
      labels:
        name: local-nvme-scratch
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        local-nvme-scratch: "true"
      priorityClassName: system-node-critical
      containers:
        - name: local-nvme-scratch
          image: {{ .Values.image }}
          imagePullPolicy: Always
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /pv-disks
              name: pv-disks
              mountPropagation: "Bidirectional"
      volumes:
        - name: pv-disks
          hostPath:
            path: /pv-disks