apiVersion: v1
kind: ServiceAccount
metadata:
  name: aksnhc-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aksnhc-role
rules:
- apiGroups: [""] # Core API group
  resources: ["nodes"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aksnhc-rolebinding
subjects:
- kind: ServiceAccount
  name: aksnhc-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: aksnhc-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
spec:
  completions: {{ .Values.numNodes }}
  parallelism: {{ .Values.numNodes }}
  completionMode: Indexed
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: aksnhc-sa
      containers:
        - name: healthcheck
          image: {{ .Values.image }}
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /dev/shm
              name: shmem
            - mountPath: /azure-nhc/syslog
              name: syslog-volume
              readOnly: true 
          resources:
            requests:
              nvidia.com/gpu: 8
              nvidia.com/mlnxnics: 8
            limits:
              nvidia.com/gpu: 8
              nvidia.com/mlnxnics: 8
          workingDir: /azure-nhc
          command: 
            - /bin/bash
            - -c
            - |
              #sed -i 's/check_nccl_allreduce 460.0/check_nccl_allreduce 480.0/g' /azure-nhc/conf/aznhc.conf
              /azure-nhc/run-healthcheck.sh
      restartPolicy: Never
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 128Gi
        name: shmem
      - name: syslog-volume
        hostPath:
          path: /var/log/syslog
          type: File
  backoffLimit: 0 # Do not retry creating job if error