ARG FROM_IMAGE_NAME=ubuntu

FROM ${FROM_IMAGE_NAME}

RUN apt update && apt install -y git python3 python3-pip vim wget
RUN cd /etc && wget https://raw.githubusercontent.com/Azure/azhpc-images/master/topology/ndv5-topo.xml    

RUN pip install --upgrade pip

RUN cd /opt && \
    git clone -b v0.2.5 https://github.com/allenai/OLMo.git && \
    cd OLMo && \
    pip install -e .[all]

RUN sed -i 's|r2://|file:///scratch/|g' /opt/OLMo/configs/official/OLMo-*

