apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: {{ .Release.Name }}-pv-blob-input
spec:
  capacity:
    storage: 8192Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - -o allow_other
    - --block-cache
    - --block-cache-path=/mnt/blobfuse
    - --block-cache-block-size=0.00390625
    #- --block-cache-block-size=0.0078125
    #- --block-cache-block-size=0.015625
    #- --block-cache-block-size=0.03125
    #- --block-cache-block-size=0.0625
    #- --block-cache-block-size=0.125
    #- --block-cache-block-size=0.250
    #- --block-cache-block-size=0.5
    - --block-cache-disk-size=102400
    - --block-cache-disk-timeout=604800
    - --block-cache-pool-size=1024
    - --block-cache-parallelism=128
    - --block-cache-prefetch=0
    - --block-cache-prefetch-on-open=false
    - --use-adls=false
  csi:
    driver: blob.csi.azure.com
    volumeHandle: "{{ .Values.storageAccount }}_{{ .Values.containerName }}"
    volumeAttributes:
      protocol: fuse2
      storageAccount: "{{ .Values.storageAccount }}"
      containerName: "{{ .Values.containerName }}"
      use-adls: "false"
    nodeStageSecretRef:
      name: "{{ .Values.storageAccount }}-{{ .Values.containerName }}-sas-token"
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc-blob-input
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 8192Gi
  volumeName: {{ .Release.Name }}-pv-blob-input
  storageClassName: azureblob-fuse-premium