---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc-localdisk
spec:
  storageClassName: local-disk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi