apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jupyterlab
  labels:
    name: jupyterlab
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    name: jupyterlab